config/routes.rb
IdeaStorming::Application.routes.draw do
  get "calificacion/index"
  
  get "calificacion/update"

  post "calificacion/new"

  get "calificacion/show"

  get "proyecto/index"

  post "proyecto/new"

  get "proyecto/edit"

  post "registro_proyecto/index"
  
  post "registro_user/login"

  post "registro_user/index"

  get "sitio/perfil_usuario"

  get "sitio/index"

  get "sitio/publicacion_proyecto"

  get "sitio/ficha_proyecto"

  get "sitio/calificacion_proyecto"
resources :proyecto
resources :user
resources :calificarcion

   root :to => 'sitio#index'
   match "/home" => "sitio#index" , :as => :home
   match "/registro" => "registro_user#index" , :as => :registro
   match "/calificacionproyecto" => "sitio#calificacion_proyecto" , :as => :calificacionproyecto
   match "/fichaproyecto" => "sitio#ficha_proyecto" , :as => :fichaproyecto
   match "/perfilusuario" => "sitio#perfil_usuario" , :as => :perfilusuario
   match "/publicacionproyecto" => "sitio#publicacion_proyecto" , :as => :publicacionproyecto
   match "/login" => "registro_user#login" , :as => :login
   match "/logout" => "registro_user#logout" , :as => :logout
   match "/ingresoproyecto" => "proyecto#new" , :as => :ingresoproyecto
   match "/fichaproyectousuario" =>"proyecto#index" , :ass => :fichaproyectousuario
    match "/modificarproyecto" =>"proyecto#edit" , :ass => :modificarproyecto
    match "/ingresocalificacion" =>"calificacion#new" , :ass => :ingresocalificacion

end

app/models/calificarcion.rb
class Calificarcion < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :nombre, :email , :apellido, :rut, :password,
  :message => "Campo en Blanco"

  validates_length_of :nombre , :within =>1..20, 
 :message => "20 caracteres como maximo"

  validates_length_of :password, :within =>6..25,
 :message => "minimo 6, maximo 25 caracteres"
  validates_uniqueness_of :nombre, :email, :rut
  
  validates_format_of :email, :with => /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i,
  :message => "No valido"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/calificacion_controller.rb
class CalificacionController < ApplicationController
  def index
    @titulo= "Calificacion de Proyecto"
    
  end

  def new
    if request.post?
    @calificacion=Calificarcion.new(params[:calificacion])
    p_user_id = session[:user_id]
    idu = $idproyecto
    user = User.find_by_id(p_user_id)
    @calificacion.nombreusuario= user.nombre
    @calificacion.idproyecto = idu
    if @calificacion.save
    flash[:notice]="se ha ingresado su calificacion"
    
    redirect_to :controller => "calificacion" , :action => "update"
    else
       flash[:notice]="Eror al ingresar su calificacion vuewlva a intentarlo"
    redirect_to :controller => "sitio" , :action => "index"
  end
    end
  end

  def show
  end
  def update
    nota = 0
<<<<<<< HEAD
    cont = 0
=======
>>>>>>> ede85c36334ace739e4f308640d3130f1dee9dea
    @proyecto=Proyecto.find_by_id($idproyecto)
    @calificacion=Calificarcion.all
     @calificacion.each do |c| 
       if c.idproyecto == @proyecto.id
         nota = nota + c.nota
<<<<<<< HEAD
         cont = cont + 1
         
       end  
       end
       notafinal= nota/cont
       @proyecto.calificacion=notafinal
       @proyecto.save
       flash[:notice]="se ingreso su nota correctamente"
       redirect_to home_url
     end
    

=======
         @proyecto.calificacion=nota
           
       end
     end
    redirect_to home_url
  end
>>>>>>> ede85c36334ace739e4f308640d3130f1dee9dea
end

app/controllers/proyecto_controller.rb
class ProyectoController < ApplicationController
  def index
     @titulo = "Tus Proyectos"
     @proyecto=Proyecto.all
  

   
   
 
  end
  def new
    @titulo = "Ingreso de Nuevo Proyecto"
     if request.post?
      @proyecto= Proyecto.new(params[:proyecto])
      @proyecto.idusuario= session[:user_id]
    
      if @proyecto.save
        
     flash[:notice] = "El proyecto #{@proyecto.titulo} se ha ingresado correctamente"
       redirect_to :controller => "sitio" , :action => "index"
       
    
     end
      end  
    end


  def edit
    @titulo= "Ficha de Proyectos"
    @proyecto = Proyecto.all
    respond_to do |format|
      format.html
      format.xml
    end
  end
 def show
   @titulo= "Detalles de Proyecto"
    @proyecto = Proyecto.find(params[:id])
  end
  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy
    redirect_to home_url
    
  end
end

app/controllers/registro_user_controller.rb
class RegistroUserController < ApplicationController
  def index
     @titulo = "Registro Nuevo Usuario"
    if request.post?
      @user= User.new(params[:user])
     if @user.save
       flash[:notice] = "El Usuario #{@user.nombre} se ha ingresado correctamente"
       redirect_to :controller => "sitio" , :action => "index"
     end
    end
  end
  def login
     @titulo = "Ingreso Usuario"
     if request.post?
       p_user = User.new(params[:user])
       user = User.find_by_email_and_password(p_user.email, p_user.password) 
      
      if user
         session[:user_id] = user.id
         flash[:notice] = "Hola #{user.nombre}  Bienvenido a tu Cuenta"
         redirect_to home_url
       else
         flash[:notice] = "Email/Password incorrecto"
         redirect_to login_url
       end
     end
  end
  def logout
    session[:user_id] = nil
    flash[:notice] = "Adios amigo"
    redirect_to home_url
  end
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def perfil_usuario
    @titulo = "Perfil usuario" 
    p_user=session[:user_id]
    @user = User.find_by_id(p_user)
    
      
   
  end

  def index
    @titulo = "Principal"
    @proyecto1 = Proyecto.all
    @proyecto=@proyecto1.sort_by(&:created_at).reverse
    @proyecto2=@proyecto1.sort_by(&:calificacion).reverse
  end

  def publicacion_proyecto
  end

  def ficha_proyecto
    @titulo ="Ficha de Proyectos"
 
  end

  def calificacion_proyecto
    @titulo ="Calificacion Proyecto"
    @proyecto = Proyecto.all
  end
  def show
    @proyecto = Proyecto.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calificacion_helper.rb
module CalificacionHelper
end

app/helpers/proyecto_helper.rb
module ProyectoHelper
end

app/helpers/registro_proyecto_helper.rb
module RegistroProyectoHelper
end

app/helpers/registro_user_helper.rb
module RegistroUserHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/calificacion/new.html.erb
  <%= form_for :calificacion do |c| %>
      error_messages_for "proyecto"  
    <p>
      <%= c.label "nota del 1 al 10" %>
      <%=  c.text_field :nota%>
    </p>
    <p>
      <%= c.label "Ingrese su comentario" %>
      <%=  c.text_field :comentario%>
    </p>
    
    <p>
      <%=  c.submit "Enviar"%>
    </p>
  
  <% end %>
   

app/views/calificacion/show.html.erb
<h1>Calificacion#show</h1>
<p>Find me in app/views/calificacion/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%@titulo%> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="pagina">
    <div id="cabecera">
      <h1><%=@titulo%></h1>
    </div>
    <div id="menu">
    <%=link_to_unless_current "Principal" , home_url %>
    <% if  not session[:user_id] %>
      
    <%=link_to_unless_current "Login" , login_url %>
    <%=link_to_unless_current "Registro Usuario" , registro_url %>
    <% else %>
    <%=link_to_unless_current "Calificar Proyecto" ,calificacionproyecto_url  %>
    <%=link_to_unless_current "Ficha Proyecto" , fichaproyectousuario_url %>
    <%=link_to_unless_current "Perfil Usuario" , perfilusuario_url %>
    <%=link_to_unless_current "Publicar Proyecto" , ingresoproyecto_url  %>
    <%=link_to_unless_current "Salir" , logout_url %>
    <% end  %>
     <div id="contenido">
      <%=yield %>
  </div>
  <%if ENV["RAILS_ENV"] == "development"%>
    <%=  debug(params)%>
    <% end %>
  </div>
  
</body>
</html>

app/views/proyecto/index.html.erb
<h1>Proyectos</h1>
<% p_user=session[:user_id] %>
<% user = User.find_by_id(p_user)%>
<% @proyecto.each do |p| %>
 <%if p.idusuario == p_user  %> 
  <p>
  <%= p.titulo%>

  <%=link_to "Ver mas.."  , p %>
  </p>
  <% end %>
<% end %>

app/views/proyecto/new.html.erb
<h1>Complete los campos de Proyecto</h1>
<%= form_for :proyecto do |f| %>
    <p>
      <%= f.label "Titulo" %>
      <%=  f.text_field :titulo%>
    </p>
    <p>
      <%= f.label "Nivel de Inversion" %>
      <%=  f.text_field :nivelinversion%>
    </p>

    <p>
      <%= f.label "Ventajas Comparativas" %>
      <%=  f.text_field :ventajascomparativas%>
    </p>

    <p>
      <%= f.label "Resumen" %>
      <%=  f.text_field :resumen%>
   
    </p>
    <p>
      <%=  f.submit "Enviar" %>
    </p>
  
  <% end %>

app/views/proyecto/show.html.erb
<h1> <%=@proyecto.titulo%> </h1>
<br><%=  @proyecto.resumen %></br>
<%  $idproyecto = @proyecto.id%>
<% if  session[:user_id] %>
 <%if @proyecto.idusuario != session[:user_id] %>
  <%=  link_to "calificar",ingresocalificacion_url %>

 <%end%>
<%end%>

app/views/registro_user/index.html.erb
<%= form_for :user do |f| %>
<%= error_messages_for "user"  %>
    <p>
      <%= f.label :nombre %>
      <%=  f.text_field :nombre%>
    </p>
    <p>
      <%= f.label :apellido %>
      <%=  f.text_field :apellido%>
    </p>

    <p>
      <%= f.label :rut %>
      <%=  f.text_field :rut%>
    </p>

    <p>
      <%= f.label :email %>
      <%=  f.text_field :email%>
    </p>
    <p>
      <%= f.label :password %>
      <%=  f.password_field :password%>
    </p>
    <p>
      <%=  f.submit "Guardar" %>
    </p>
  <% end %>

app/views/registro_user/login.html.erb
<%=  flash[:notice] %>
<%= form_for :user do |f| %>
<%= error_messages_for "user"  %>

    <p>
      <%= f.label :email %>
      <%=  f.text_field :email%>
    </p>
    <p>
      <%= f.label :password %>
      <%=  f.password_field :password%>
    </p>
    <p>
      <%=  f.submit "Entrar" %>
    </p>
  <% end %>

app/views/sitio/calificacion_proyecto.html.erb
<h1>Proyectos</h1>
<%  @proyecto.each  do |p| %>
<p> 
<%= p.titulo %>
<%= link_to  "calificar", p %>
</p>
<%  end %>

app/views/sitio/index.html.erb
<%=  flash[:notice] %>
<h1>Bienvenido a IdeaStorm</h1>
<h1>Los  Ultimos 20 Proyectos</h1>
<% @cont = 0 %>
<% @proyecto.each do |p| %>
  <% if @cont < 20 %>
   <p>
   <%= p.titulo%>

   <%=link_to "Ver mas.."  , p %>
   </p>
   <% end %>
<% @cont = @cont + 1 %>
<% end %>
<h1>Los 20 Proyectos mas Populares</h1>
<% @cont = 0 %>
<% @proyecto2.each do |p| %>
  <% if @cont < 20 %>
   <p>
   <%= p.titulo%>

   <%=link_to "Ver mas.."  , p %>
   </p>
   <% end %>
<% @cont = @cont + 1 %>
<% end %>

app/views/sitio/perfil_usuario.html.erb
<p>
<p>
<%= @user.nombre%>
</p>
<p>
<%= @user.apellido%>

</p>
<p>
<%= @user.rut%>

</p>
<p>
<%= @user.email%>

</p>